name: Upload Release Asset

on:

  # Trigger the workflow on push or pull request,

  # but only for the master branch

  push:

    branches:

      - master
    tags: 
      - 'v*'
      

jobs:

  build:

    name: Upload Release Asset

    runs-on: windows-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Creating distribution Server
        working-directory: ./Server
        run: |
          pyinstaller server.py
          mv dist dist-server
          mv dist-server ..
      - name: Creating distribution Client
        working-directory: ./Client
        run: |
          pyinstaller client.py
          mv dist dist-client
          mv dist-client ..
      - name: Create zip of client
        run: 
          powershell.exe compress-archive dist-client release-client
      - name: Create zip of server
        run: 
          powershell.exe compress-archive dist-server release-server
      
      - name: Create Release

        id: create_release

        uses: actions/create-release@v1.0.0

        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:

          tag_name: ${{ github.ref }}

          release_name: Release ${{ github.ref }}

          draft: false

          prerelease: false

      - name: Release client
        uses: AButler/upload-release-assets@v2.0
        with: 
          files: 'release-client.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag:  ${{ github.ref }}

      - name: Release server
        uses: AButler/upload-release-assets@v2.0
        with: 
          files: 'release-server.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag:  ${{ github.ref }}
      