# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python application

on:
  push:
    branches: [ master ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  Release:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Creating distribution Server
      working-directory: ./Server
      run: |
        make exe
        mv dist dist-server
        mv dist-server ..
    - name: Creating distribution Client
      working-directory: ./Client
      run: |
       make exe
       mv dist dist-client
       mv dist-client ..
    - name: move release files to release folder
      run: |
        mkdir release
        mv -v dist-server ./release
        mv -v dist-client ./release
    - name: Zip the release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: 'makefile requirement.txt README.md /*Server/* /*Client/* /*Test/* '
    - name: Release to github
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        file: release.zip
        asset_name: server-client
        tag: ${{ github.ref }}
        overwrite: true        
    

       
