# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Release:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Creating distribution Server
      working-directory: ./Server
      run: |
        make exe
        mv dist dist-server
        mv dist-server ..
    - name: Creating distribution Client
      working-directory: ./Client
      run: |
       make exe
       mv dist dist-client
       mv dist-client ..
    - name: Test if folders got moved
      run: |
        ls

      
        
    

       
